apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-world
  namespace: dev
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: hello-world
